#pragma once
// Checks shared by the end-to-end tests: every output byte the clients and the feed
// received equals what journal_replay --emit regenerates from the journal (T05, 06 §12:
// "every engine output can be regenerated byte for byte from the journal"), the output
// log equals it too (06 §8, Outlog.RegeneratesFromJournal), and our feed passes
// itch_validate --strict (T06: "0 validator errors on our feed").
#include <filesystem>
#include <map>
#include <string>
#include <vector>

#include "harness.h"

namespace lle::exch::test {

struct Regenerated {
  std::vector<Bytes> itch;
  std::map<std::uint32_t, Bytes> ouch;  // per session, [u16 length][message]
  std::string report;
  int exit_code = -1;
};

inline Regenerated regenerate(const std::string& journal_dir, const std::filesystem::path& out) {
  std::filesystem::create_directories(out);
  const std::string itch = (out / "regen-itch.bin").string();
  const std::string ouch = (out / "regen-ouch.bin").string();
  Regenerated r;
  r.report = run_capture({LLE_JOURNAL_REPLAY, journal_dir, "--emit", itch, "--emit-ouch", ouch}, &r.exit_code);
  r.itch = split_binary_file(slurp(itch));
  r.ouch = split_ouch(slurp(ouch));
  return r;
}

// An output-log data file is BinaryFILE framing without the end record.
inline Bytes outlog_bytes(const std::string& path) { return slurp(path); }

inline Bytes framed(const std::vector<Bytes>& msgs) {
  Bytes out;
  for (const Bytes& m : msgs) {
    std::byte len[2];
    store_be16(len, static_cast<std::uint16_t>(m.size()));
    out.insert(out.end(), len, len + 2);
    out.insert(out.end(), m.begin(), m.end());
  }
  return out;
}

struct ValidateResult {
  int exit_code = -1;
  std::string report;
  std::uint64_t messages = 0;
  std::uint64_t violations = ~std::uint64_t{0};
};

inline ValidateResult itch_validate(const std::string& binary_file) {
  ValidateResult v;
  v.report = run_capture({LLE_ITCH_VALIDATE, "--strict", binary_file}, &v.exit_code);
  const auto m = v.report.find("messages ");
  if (m != std::string::npos) v.messages = std::stoull(v.report.substr(m + 9));
  const auto at = v.report.find("violations ");
  if (at != std::string::npos) v.violations = std::stoull(v.report.substr(at + 11));
  return v;
}

}  // namespace lle::exch::test
