// GENERATED by tools/specgen/specgen.py from src/proto/ouch50/spec/ouch50_fields.csv.
// DO NOT EDIT. Regenerate with: python3 tools/specgen/specgen.py
// OUCH 5.0 rev 1.05 (Nasdaq, updated October 2025).
#pragma once
#include <cstddef>
#include <cstdint>
#include <span>
#include <utility>

#include "common/alpha.h"
#include "common/endian.h"
#include "proto/ouch50/message_view.h"
#include "proto/ouch50/ouch50_layout.gen.h"
#include "proto/ouch50/tagvalue.h"

namespace lle::ouch50 {

enum class InboundType : char {
  EnterOrder = 'O',
  ReplaceOrder = 'U',
  CancelOrder = 'X',
  ModifyOrder = 'M',
  MassCancel = 'C',
  DisableOrderEntry = 'D',
  EnableOrderEntry = 'E',
  AccountQuery = 'Q',
};
enum class OutboundType : char {
  SystemEvent = 'S',
  OrderAccepted = 'A',
  OrderReplaced = 'U',
  OrderCanceled = 'C',
  AiqCanceled = 'D',
  OrderExecuted = 'E',
  BrokenTrade = 'B',
  Rejected = 'J',
  CancelPending = 'P',
  CancelReject = 'I',
  OrderPriorityUpdate = 'T',
  OrderModified = 'M',
  OrderRestated = 'R',
  MassCancelResponse = 'X',
  DisableOrderEntryResponse = 'G',
  EnableOrderEntryResponse = 'K',
  AccountQueryResponse = 'Q',
};

namespace in {

// s2.1 Enter Order
struct EnterOrder {
  using Layout = layout::in::EnterOrder;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "EnterOrder";

  std::uint32_t user_ref_num{};
  Side side{Side::Buy};
  std::uint32_t quantity{};
  Alpha<8> symbol{};
  std::uint64_t price{};
  TimeInForce time_in_force{TimeInForce::Day};
  Display display{Display::Visible};
  Capacity capacity{Capacity::Agency};
  IsoEligibility inter_market_sweep_eligibility{IsoEligibility::Eligible};
  CrossType cross_type{CrossType::Continuous};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    p[5] = static_cast<std::byte>(std::to_underlying(side));
    store_be32(p + 6, quantity);
    symbol.to_wire(p + 10);
    store_be64(p + 18, price);
    p[26] = static_cast<std::byte>(std::to_underlying(time_in_force));
    p[27] = static_cast<std::byte>(std::to_underlying(display));
    p[28] = static_cast<std::byte>(std::to_underlying(capacity));
    p[29] = static_cast<std::byte>(std::to_underlying(inter_market_sweep_eligibility));
    p[30] = static_cast<std::byte>(std::to_underlying(cross_type));
    cl_ord_id.to_wire(p + 31);
  }
  [[nodiscard]] static EnterOrder decode_base(const std::byte* p) noexcept {
    EnterOrder m;
    m.user_ref_num = load_be32(p + 1);
    m.side = static_cast<Side>(std::to_integer<char>(p[5]));
    m.quantity = load_be32(p + 6);
    m.symbol = Alpha<8>::from_wire(p + 10);
    m.price = load_be64(p + 18);
    m.time_in_force = static_cast<TimeInForce>(std::to_integer<char>(p[26]));
    m.display = static_cast<Display>(std::to_integer<char>(p[27]));
    m.capacity = static_cast<Capacity>(std::to_integer<char>(p[28]));
    m.inter_market_sweep_eligibility = static_cast<IsoEligibility>(std::to_integer<char>(p[29]));
    m.cross_type = static_cast<CrossType>(std::to_integer<char>(p[30]));
    m.cl_ord_id = Alpha<14>::from_wire(p + 31);
    return m;
  }
  friend bool operator==(const EnterOrder&, const EnterOrder&) = default;
};

class EnterOrderView : public MessageView<EnterOrder> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] Side side() const noexcept { return static_cast<Side>(std::to_integer<char>(p()[5])); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 6); }
  [[nodiscard]] Alpha<8> symbol() const noexcept { return Alpha<8>::from_wire(p() + 10); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 18); }
  [[nodiscard]] TimeInForce time_in_force() const noexcept { return static_cast<TimeInForce>(std::to_integer<char>(p()[26])); }
  [[nodiscard]] Display display() const noexcept { return static_cast<Display>(std::to_integer<char>(p()[27])); }
  [[nodiscard]] Capacity capacity() const noexcept { return static_cast<Capacity>(std::to_integer<char>(p()[28])); }
  [[nodiscard]] IsoEligibility inter_market_sweep_eligibility() const noexcept { return static_cast<IsoEligibility>(std::to_integer<char>(p()[29])); }
  [[nodiscard]] CrossType cross_type() const noexcept { return static_cast<CrossType>(std::to_integer<char>(p()[30])); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 31); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const EnterOrderView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Side", v.side());
  f("Quantity", v.quantity());
  f("Symbol", v.symbol());
  f("Price", v.price());
  f("TimeInForce", v.time_in_force());
  f("Display", v.display());
  f("Capacity", v.capacity());
  f("InterMarketSweepEligibility", v.inter_market_sweep_eligibility());
  f("CrossType", v.cross_type());
  f("ClOrdID", v.cl_ord_id());
}

// s2.2 Replace Order Request; Firm and GroupID are inherited from the original order
struct ReplaceOrder {
  using Layout = layout::in::ReplaceOrder;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "ReplaceOrder";

  std::uint32_t orig_user_ref_num{};
  std::uint32_t user_ref_num{};
  std::uint32_t quantity{};
  std::uint64_t price{};
  TimeInForce time_in_force{TimeInForce::Day};
  Display display{Display::Visible};
  IsoEligibility inter_market_sweep_eligibility{IsoEligibility::Eligible};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, orig_user_ref_num);
    store_be32(p + 5, user_ref_num);
    store_be32(p + 9, quantity);
    store_be64(p + 13, price);
    p[21] = static_cast<std::byte>(std::to_underlying(time_in_force));
    p[22] = static_cast<std::byte>(std::to_underlying(display));
    p[23] = static_cast<std::byte>(std::to_underlying(inter_market_sweep_eligibility));
    cl_ord_id.to_wire(p + 24);
  }
  [[nodiscard]] static ReplaceOrder decode_base(const std::byte* p) noexcept {
    ReplaceOrder m;
    m.orig_user_ref_num = load_be32(p + 1);
    m.user_ref_num = load_be32(p + 5);
    m.quantity = load_be32(p + 9);
    m.price = load_be64(p + 13);
    m.time_in_force = static_cast<TimeInForce>(std::to_integer<char>(p[21]));
    m.display = static_cast<Display>(std::to_integer<char>(p[22]));
    m.inter_market_sweep_eligibility = static_cast<IsoEligibility>(std::to_integer<char>(p[23]));
    m.cl_ord_id = Alpha<14>::from_wire(p + 24);
    return m;
  }
  friend bool operator==(const ReplaceOrder&, const ReplaceOrder&) = default;
};

class ReplaceOrderView : public MessageView<ReplaceOrder> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t orig_user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 5); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 13); }
  [[nodiscard]] TimeInForce time_in_force() const noexcept { return static_cast<TimeInForce>(std::to_integer<char>(p()[21])); }
  [[nodiscard]] Display display() const noexcept { return static_cast<Display>(std::to_integer<char>(p()[22])); }
  [[nodiscard]] IsoEligibility inter_market_sweep_eligibility() const noexcept { return static_cast<IsoEligibility>(std::to_integer<char>(p()[23])); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 24); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const ReplaceOrderView& v, F&& f) {
  f("OrigUserRefNum", v.orig_user_ref_num());
  f("UserRefNum", v.user_ref_num());
  f("Quantity", v.quantity());
  f("Price", v.price());
  f("TimeInForce", v.time_in_force());
  f("Display", v.display());
  f("InterMarketSweepEligibility", v.inter_market_sweep_eligibility());
  f("ClOrdID", v.cl_ord_id());
}

// s2.3 Cancel Order Request; Appendage Length may be omitted
struct CancelOrder {
  using Layout = layout::in::CancelOrder;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "CancelOrder";

  std::uint32_t user_ref_num{};
  std::uint32_t quantity{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    store_be32(p + 5, quantity);
  }
  [[nodiscard]] static CancelOrder decode_base(const std::byte* p) noexcept {
    CancelOrder m;
    m.user_ref_num = load_be32(p + 1);
    m.quantity = load_be32(p + 5);
    return m;
  }
  friend bool operator==(const CancelOrder&, const CancelOrder&) = default;
};

class CancelOrderView : public MessageView<CancelOrder> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 5); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const CancelOrderView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Quantity", v.quantity());
}

// s2.4 Modify Order Request; Appendage Length may be omitted
struct ModifyOrder {
  using Layout = layout::in::ModifyOrder;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "ModifyOrder";

  std::uint32_t user_ref_num{};
  Side side{Side::Buy};
  std::uint32_t quantity{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    p[5] = static_cast<std::byte>(std::to_underlying(side));
    store_be32(p + 6, quantity);
  }
  [[nodiscard]] static ModifyOrder decode_base(const std::byte* p) noexcept {
    ModifyOrder m;
    m.user_ref_num = load_be32(p + 1);
    m.side = static_cast<Side>(std::to_integer<char>(p[5]));
    m.quantity = load_be32(p + 6);
    return m;
  }
  friend bool operator==(const ModifyOrder&, const ModifyOrder&) = default;
};

class ModifyOrderView : public MessageView<ModifyOrder> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] Side side() const noexcept { return static_cast<Side>(std::to_integer<char>(p()[5])); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 6); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const ModifyOrderView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Side", v.side());
  f("Quantity", v.quantity());
}

// s2.5 Mass Cancel Request
struct MassCancel {
  using Layout = layout::in::MassCancel;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "MassCancel";

  std::uint32_t user_ref_num{};
  Alpha<4> firm{};
  Alpha<8> symbol{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    firm.to_wire(p + 5);
    symbol.to_wire(p + 9);
  }
  [[nodiscard]] static MassCancel decode_base(const std::byte* p) noexcept {
    MassCancel m;
    m.user_ref_num = load_be32(p + 1);
    m.firm = Alpha<4>::from_wire(p + 5);
    m.symbol = Alpha<8>::from_wire(p + 9);
    return m;
  }
  friend bool operator==(const MassCancel&, const MassCancel&) = default;
};

class MassCancelView : public MessageView<MassCancel> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 5); }
  [[nodiscard]] Alpha<8> symbol() const noexcept { return Alpha<8>::from_wire(p() + 9); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const MassCancelView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
  f("Symbol", v.symbol());
}

// s2.6 Disable Order Entry Request
struct DisableOrderEntry {
  using Layout = layout::in::DisableOrderEntry;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "DisableOrderEntry";

  std::uint32_t user_ref_num{};
  Alpha<4> firm{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    firm.to_wire(p + 5);
  }
  [[nodiscard]] static DisableOrderEntry decode_base(const std::byte* p) noexcept {
    DisableOrderEntry m;
    m.user_ref_num = load_be32(p + 1);
    m.firm = Alpha<4>::from_wire(p + 5);
    return m;
  }
  friend bool operator==(const DisableOrderEntry&, const DisableOrderEntry&) = default;
};

class DisableOrderEntryView : public MessageView<DisableOrderEntry> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 5); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const DisableOrderEntryView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
}

// s2.7 Enable Order Entry Request
struct EnableOrderEntry {
  using Layout = layout::in::EnableOrderEntry;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "EnableOrderEntry";

  std::uint32_t user_ref_num{};
  Alpha<4> firm{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be32(p + 1, user_ref_num);
    firm.to_wire(p + 5);
  }
  [[nodiscard]] static EnableOrderEntry decode_base(const std::byte* p) noexcept {
    EnableOrderEntry m;
    m.user_ref_num = load_be32(p + 1);
    m.firm = Alpha<4>::from_wire(p + 5);
    return m;
  }
  friend bool operator==(const EnableOrderEntry&, const EnableOrderEntry&) = default;
};

class EnableOrderEntryView : public MessageView<EnableOrderEntry> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 1); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 5); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const EnableOrderEntryView& v, F&& f) {
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
}

// s2.8 Account Query Request; Appendage Length may be omitted
struct AccountQuery {
  using Layout = layout::in::AccountQuery;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Inbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "AccountQuery";


  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
  }
  [[nodiscard]] static AccountQuery decode_base(const std::byte* p) noexcept {
    AccountQuery m;
    (void)p;
    return m;
  }
  friend bool operator==(const AccountQuery&, const AccountQuery&) = default;
};

class AccountQueryView : public MessageView<AccountQuery> {
 public:
  using MessageView::MessageView;
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const AccountQueryView& v, F&& f) {
  (void)v;
  (void)f;
}

}  // namespace in

namespace out {

// s3.1 System Event (no appendage)
struct SystemEvent {
  using Layout = layout::out::SystemEvent;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "SystemEvent";

  std::uint64_t timestamp{};
  EventCode event_code{EventCode::StartOfDay};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    p[9] = static_cast<std::byte>(std::to_underlying(event_code));
  }
  [[nodiscard]] static SystemEvent decode_base(const std::byte* p) noexcept {
    SystemEvent m;
    m.timestamp = load_be64(p + 1);
    m.event_code = static_cast<EventCode>(std::to_integer<char>(p[9]));
    return m;
  }
  friend bool operator==(const SystemEvent&, const SystemEvent&) = default;
};

class SystemEventView : public MessageView<SystemEvent> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] EventCode event_code() const noexcept { return static_cast<EventCode>(std::to_integer<char>(p()[9])); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const SystemEventView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("EventCode", v.event_code());
}

// s3.2 Order Accepted
struct OrderAccepted {
  using Layout = layout::out::OrderAccepted;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderAccepted";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  Side side{Side::Buy};
  std::uint32_t quantity{};
  Alpha<8> symbol{};
  std::uint64_t price{};
  TimeInForce time_in_force{TimeInForce::Day};
  Display display{Display::Visible};
  std::uint64_t order_reference_number{};
  Capacity capacity{Capacity::Agency};
  IsoEligibility inter_market_sweep_eligibility{IsoEligibility::Eligible};
  CrossType cross_type{CrossType::Continuous};
  OrderState order_state{OrderState::Live};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    p[13] = static_cast<std::byte>(std::to_underlying(side));
    store_be32(p + 14, quantity);
    symbol.to_wire(p + 18);
    store_be64(p + 26, price);
    p[34] = static_cast<std::byte>(std::to_underlying(time_in_force));
    p[35] = static_cast<std::byte>(std::to_underlying(display));
    store_be64(p + 36, order_reference_number);
    p[44] = static_cast<std::byte>(std::to_underlying(capacity));
    p[45] = static_cast<std::byte>(std::to_underlying(inter_market_sweep_eligibility));
    p[46] = static_cast<std::byte>(std::to_underlying(cross_type));
    p[47] = static_cast<std::byte>(std::to_underlying(order_state));
    cl_ord_id.to_wire(p + 48);
  }
  [[nodiscard]] static OrderAccepted decode_base(const std::byte* p) noexcept {
    OrderAccepted m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.side = static_cast<Side>(std::to_integer<char>(p[13]));
    m.quantity = load_be32(p + 14);
    m.symbol = Alpha<8>::from_wire(p + 18);
    m.price = load_be64(p + 26);
    m.time_in_force = static_cast<TimeInForce>(std::to_integer<char>(p[34]));
    m.display = static_cast<Display>(std::to_integer<char>(p[35]));
    m.order_reference_number = load_be64(p + 36);
    m.capacity = static_cast<Capacity>(std::to_integer<char>(p[44]));
    m.inter_market_sweep_eligibility = static_cast<IsoEligibility>(std::to_integer<char>(p[45]));
    m.cross_type = static_cast<CrossType>(std::to_integer<char>(p[46]));
    m.order_state = static_cast<OrderState>(std::to_integer<char>(p[47]));
    m.cl_ord_id = Alpha<14>::from_wire(p + 48);
    return m;
  }
  friend bool operator==(const OrderAccepted&, const OrderAccepted&) = default;
};

class OrderAcceptedView : public MessageView<OrderAccepted> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] Side side() const noexcept { return static_cast<Side>(std::to_integer<char>(p()[13])); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 14); }
  [[nodiscard]] Alpha<8> symbol() const noexcept { return Alpha<8>::from_wire(p() + 18); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 26); }
  [[nodiscard]] TimeInForce time_in_force() const noexcept { return static_cast<TimeInForce>(std::to_integer<char>(p()[34])); }
  [[nodiscard]] Display display() const noexcept { return static_cast<Display>(std::to_integer<char>(p()[35])); }
  [[nodiscard]] std::uint64_t order_reference_number() const noexcept { return load_be64(p() + 36); }
  [[nodiscard]] Capacity capacity() const noexcept { return static_cast<Capacity>(std::to_integer<char>(p()[44])); }
  [[nodiscard]] IsoEligibility inter_market_sweep_eligibility() const noexcept { return static_cast<IsoEligibility>(std::to_integer<char>(p()[45])); }
  [[nodiscard]] CrossType cross_type() const noexcept { return static_cast<CrossType>(std::to_integer<char>(p()[46])); }
  [[nodiscard]] OrderState order_state() const noexcept { return static_cast<OrderState>(std::to_integer<char>(p()[47])); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 48); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderAcceptedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Side", v.side());
  f("Quantity", v.quantity());
  f("Symbol", v.symbol());
  f("Price", v.price());
  f("TimeInForce", v.time_in_force());
  f("Display", v.display());
  f("OrderReferenceNumber", v.order_reference_number());
  f("Capacity", v.capacity());
  f("InterMarketSweepEligibility", v.inter_market_sweep_eligibility());
  f("CrossType", v.cross_type());
  f("OrderState", v.order_state());
  f("ClOrdID", v.cl_ord_id());
}

// s3.3 Order Replaced
struct OrderReplaced {
  using Layout = layout::out::OrderReplaced;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderReplaced";

  std::uint64_t timestamp{};
  std::uint32_t orig_user_ref_num{};
  std::uint32_t user_ref_num{};
  Side side{Side::Buy};
  std::uint32_t quantity{};
  Alpha<8> symbol{};
  std::uint64_t price{};
  TimeInForce time_in_force{TimeInForce::Day};
  Display display{Display::Visible};
  std::uint64_t order_reference_number{};
  Capacity capacity{Capacity::Agency};
  IsoEligibility inter_market_sweep_eligibility{IsoEligibility::Eligible};
  CrossType cross_type{CrossType::Continuous};
  OrderState order_state{OrderState::Live};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, orig_user_ref_num);
    store_be32(p + 13, user_ref_num);
    p[17] = static_cast<std::byte>(std::to_underlying(side));
    store_be32(p + 18, quantity);
    symbol.to_wire(p + 22);
    store_be64(p + 30, price);
    p[38] = static_cast<std::byte>(std::to_underlying(time_in_force));
    p[39] = static_cast<std::byte>(std::to_underlying(display));
    store_be64(p + 40, order_reference_number);
    p[48] = static_cast<std::byte>(std::to_underlying(capacity));
    p[49] = static_cast<std::byte>(std::to_underlying(inter_market_sweep_eligibility));
    p[50] = static_cast<std::byte>(std::to_underlying(cross_type));
    p[51] = static_cast<std::byte>(std::to_underlying(order_state));
    cl_ord_id.to_wire(p + 52);
  }
  [[nodiscard]] static OrderReplaced decode_base(const std::byte* p) noexcept {
    OrderReplaced m;
    m.timestamp = load_be64(p + 1);
    m.orig_user_ref_num = load_be32(p + 9);
    m.user_ref_num = load_be32(p + 13);
    m.side = static_cast<Side>(std::to_integer<char>(p[17]));
    m.quantity = load_be32(p + 18);
    m.symbol = Alpha<8>::from_wire(p + 22);
    m.price = load_be64(p + 30);
    m.time_in_force = static_cast<TimeInForce>(std::to_integer<char>(p[38]));
    m.display = static_cast<Display>(std::to_integer<char>(p[39]));
    m.order_reference_number = load_be64(p + 40);
    m.capacity = static_cast<Capacity>(std::to_integer<char>(p[48]));
    m.inter_market_sweep_eligibility = static_cast<IsoEligibility>(std::to_integer<char>(p[49]));
    m.cross_type = static_cast<CrossType>(std::to_integer<char>(p[50]));
    m.order_state = static_cast<OrderState>(std::to_integer<char>(p[51]));
    m.cl_ord_id = Alpha<14>::from_wire(p + 52);
    return m;
  }
  friend bool operator==(const OrderReplaced&, const OrderReplaced&) = default;
};

class OrderReplacedView : public MessageView<OrderReplaced> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t orig_user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 13); }
  [[nodiscard]] Side side() const noexcept { return static_cast<Side>(std::to_integer<char>(p()[17])); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 18); }
  [[nodiscard]] Alpha<8> symbol() const noexcept { return Alpha<8>::from_wire(p() + 22); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 30); }
  [[nodiscard]] TimeInForce time_in_force() const noexcept { return static_cast<TimeInForce>(std::to_integer<char>(p()[38])); }
  [[nodiscard]] Display display() const noexcept { return static_cast<Display>(std::to_integer<char>(p()[39])); }
  [[nodiscard]] std::uint64_t order_reference_number() const noexcept { return load_be64(p() + 40); }
  [[nodiscard]] Capacity capacity() const noexcept { return static_cast<Capacity>(std::to_integer<char>(p()[48])); }
  [[nodiscard]] IsoEligibility inter_market_sweep_eligibility() const noexcept { return static_cast<IsoEligibility>(std::to_integer<char>(p()[49])); }
  [[nodiscard]] CrossType cross_type() const noexcept { return static_cast<CrossType>(std::to_integer<char>(p()[50])); }
  [[nodiscard]] OrderState order_state() const noexcept { return static_cast<OrderState>(std::to_integer<char>(p()[51])); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 52); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderReplacedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("OrigUserRefNum", v.orig_user_ref_num());
  f("UserRefNum", v.user_ref_num());
  f("Side", v.side());
  f("Quantity", v.quantity());
  f("Symbol", v.symbol());
  f("Price", v.price());
  f("TimeInForce", v.time_in_force());
  f("Display", v.display());
  f("OrderReferenceNumber", v.order_reference_number());
  f("Capacity", v.capacity());
  f("InterMarketSweepEligibility", v.inter_market_sweep_eligibility());
  f("CrossType", v.cross_type());
  f("OrderState", v.order_state());
  f("ClOrdID", v.cl_ord_id());
}

// s3.4 Order Canceled; appendage only with a non-zero UserRefIdx
struct OrderCanceled {
  using Layout = layout::out::OrderCanceled;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderCanceled";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  std::uint32_t quantity{};
  CancelReason reason{CancelReason::RegulatoryRestriction};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be32(p + 13, quantity);
    p[17] = static_cast<std::byte>(std::to_underlying(reason));
  }
  [[nodiscard]] static OrderCanceled decode_base(const std::byte* p) noexcept {
    OrderCanceled m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.quantity = load_be32(p + 13);
    m.reason = static_cast<CancelReason>(std::to_integer<char>(p[17]));
    return m;
  }
  friend bool operator==(const OrderCanceled&, const OrderCanceled&) = default;
};

class OrderCanceledView : public MessageView<OrderCanceled> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 13); }
  [[nodiscard]] CancelReason reason() const noexcept { return static_cast<CancelReason>(std::to_integer<char>(p()[17])); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderCanceledView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Quantity", v.quantity());
  f("Reason", v.reason());
}

// s3.5 AIQ Canceled; appendage only with a non-zero UserRefIdx
struct AiqCanceled {
  using Layout = layout::out::AiqCanceled;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "AiqCanceled";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  std::uint32_t decrement_shares{};
  CancelReason reason{CancelReason::SelfMatchPrevention};
  std::uint32_t quantity_prevented_from_trading{};
  std::uint64_t execution_price{};
  LiquidityFlag liquidity_flag{LiquidityFlag::Added};
  AiqStrategy aiq_strategy{AiqStrategy::PortDefault};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be32(p + 13, decrement_shares);
    p[17] = static_cast<std::byte>(std::to_underlying(reason));
    store_be32(p + 18, quantity_prevented_from_trading);
    store_be64(p + 22, execution_price);
    p[30] = static_cast<std::byte>(std::to_underlying(liquidity_flag));
    p[31] = static_cast<std::byte>(std::to_underlying(aiq_strategy));
  }
  [[nodiscard]] static AiqCanceled decode_base(const std::byte* p) noexcept {
    AiqCanceled m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.decrement_shares = load_be32(p + 13);
    m.reason = static_cast<CancelReason>(std::to_integer<char>(p[17]));
    m.quantity_prevented_from_trading = load_be32(p + 18);
    m.execution_price = load_be64(p + 22);
    m.liquidity_flag = static_cast<LiquidityFlag>(std::to_integer<char>(p[30]));
    m.aiq_strategy = static_cast<AiqStrategy>(std::to_integer<char>(p[31]));
    return m;
  }
  friend bool operator==(const AiqCanceled&, const AiqCanceled&) = default;
};

class AiqCanceledView : public MessageView<AiqCanceled> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint32_t decrement_shares() const noexcept { return load_be32(p() + 13); }
  [[nodiscard]] CancelReason reason() const noexcept { return static_cast<CancelReason>(std::to_integer<char>(p()[17])); }
  [[nodiscard]] std::uint32_t quantity_prevented_from_trading() const noexcept { return load_be32(p() + 18); }
  [[nodiscard]] std::uint64_t execution_price() const noexcept { return load_be64(p() + 22); }
  [[nodiscard]] LiquidityFlag liquidity_flag() const noexcept { return static_cast<LiquidityFlag>(std::to_integer<char>(p()[30])); }
  [[nodiscard]] AiqStrategy aiq_strategy() const noexcept { return static_cast<AiqStrategy>(std::to_integer<char>(p()[31])); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const AiqCanceledView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("DecrementShares", v.decrement_shares());
  f("Reason", v.reason());
  f("QuantityPreventedFromTrading", v.quantity_prevented_from_trading());
  f("ExecutionPrice", v.execution_price());
  f("LiquidityFlag", v.liquidity_flag());
  f("AIQStrategy", v.aiq_strategy());
}

// s3.6 Order Executed; Appendage Length is not marked optional (R1b risk 2)
struct OrderExecuted {
  using Layout = layout::out::OrderExecuted;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderExecuted";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  std::uint32_t quantity{};
  std::uint64_t price{};
  LiquidityFlag liquidity_flag{LiquidityFlag::Added};
  std::uint64_t match_number{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be32(p + 13, quantity);
    store_be64(p + 17, price);
    p[25] = static_cast<std::byte>(std::to_underlying(liquidity_flag));
    store_be64(p + 26, match_number);
  }
  [[nodiscard]] static OrderExecuted decode_base(const std::byte* p) noexcept {
    OrderExecuted m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.quantity = load_be32(p + 13);
    m.price = load_be64(p + 17);
    m.liquidity_flag = static_cast<LiquidityFlag>(std::to_integer<char>(p[25]));
    m.match_number = load_be64(p + 26);
    return m;
  }
  friend bool operator==(const OrderExecuted&, const OrderExecuted&) = default;
};

class OrderExecutedView : public MessageView<OrderExecuted> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 13); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 17); }
  [[nodiscard]] LiquidityFlag liquidity_flag() const noexcept { return static_cast<LiquidityFlag>(std::to_integer<char>(p()[25])); }
  [[nodiscard]] std::uint64_t match_number() const noexcept { return load_be64(p() + 26); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderExecutedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Quantity", v.quantity());
  f("Price", v.price());
  f("LiquidityFlag", v.liquidity_flag());
  f("MatchNumber", v.match_number());
}

// s3.7 Broken Trade; appendage only with a non-zero UserRefIdx
struct BrokenTrade {
  using Layout = layout::out::BrokenTrade;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "BrokenTrade";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  std::uint64_t match_number{};
  BrokenTradeReason reason{BrokenTradeReason::Erroneous};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be64(p + 13, match_number);
    p[21] = static_cast<std::byte>(std::to_underlying(reason));
    cl_ord_id.to_wire(p + 22);
  }
  [[nodiscard]] static BrokenTrade decode_base(const std::byte* p) noexcept {
    BrokenTrade m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.match_number = load_be64(p + 13);
    m.reason = static_cast<BrokenTradeReason>(std::to_integer<char>(p[21]));
    m.cl_ord_id = Alpha<14>::from_wire(p + 22);
    return m;
  }
  friend bool operator==(const BrokenTrade&, const BrokenTrade&) = default;
};

class BrokenTradeView : public MessageView<BrokenTrade> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint64_t match_number() const noexcept { return load_be64(p() + 13); }
  [[nodiscard]] BrokenTradeReason reason() const noexcept { return static_cast<BrokenTradeReason>(std::to_integer<char>(p()[21])); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 22); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const BrokenTradeView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("MatchNumber", v.match_number());
  f("Reason", v.reason());
  f("ClOrdID", v.cl_ord_id());
}

// s3.8 Rejected; appendage only with a non-zero UserRefIdx
struct Rejected {
  using Layout = layout::out::Rejected;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "Rejected";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  RejectReason reason{RejectReason::QuoteUnavailable};
  Alpha<14> cl_ord_id{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be16(p + 13, static_cast<std::uint16_t>(reason));
    cl_ord_id.to_wire(p + 15);
  }
  [[nodiscard]] static Rejected decode_base(const std::byte* p) noexcept {
    Rejected m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.reason = static_cast<RejectReason>(load_be16(p + 13));
    m.cl_ord_id = Alpha<14>::from_wire(p + 15);
    return m;
  }
  friend bool operator==(const Rejected&, const Rejected&) = default;
};

class RejectedView : public MessageView<Rejected> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] RejectReason reason() const noexcept { return static_cast<RejectReason>(load_be16(p() + 13)); }
  [[nodiscard]] Alpha<14> cl_ord_id() const noexcept { return Alpha<14>::from_wire(p() + 15); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const RejectedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Reason", v.reason());
  f("ClOrdID", v.cl_ord_id());
}

// s3.9 Cancel Pending; appendage only with a non-zero UserRefIdx
struct CancelPending {
  using Layout = layout::out::CancelPending;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "CancelPending";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
  }
  [[nodiscard]] static CancelPending decode_base(const std::byte* p) noexcept {
    CancelPending m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    return m;
  }
  friend bool operator==(const CancelPending&, const CancelPending&) = default;
};

class CancelPendingView : public MessageView<CancelPending> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const CancelPendingView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
}

// s3.10 Cancel Reject; appendage only with a non-zero UserRefIdx
struct CancelReject {
  using Layout = layout::out::CancelReject;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "CancelReject";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
  }
  [[nodiscard]] static CancelReject decode_base(const std::byte* p) noexcept {
    CancelReject m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    return m;
  }
  friend bool operator==(const CancelReject&, const CancelReject&) = default;
};

class CancelRejectView : public MessageView<CancelReject> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const CancelRejectView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
}

// s3.11 Order Priority Update; appendage only with a non-zero UserRefIdx
struct OrderPriorityUpdate {
  using Layout = layout::out::OrderPriorityUpdate;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderPriorityUpdate";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  std::uint64_t price{};
  Display display{Display::Visible};
  std::uint64_t order_reference_number{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    store_be64(p + 13, price);
    p[21] = static_cast<std::byte>(std::to_underlying(display));
    store_be64(p + 22, order_reference_number);
  }
  [[nodiscard]] static OrderPriorityUpdate decode_base(const std::byte* p) noexcept {
    OrderPriorityUpdate m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.price = load_be64(p + 13);
    m.display = static_cast<Display>(std::to_integer<char>(p[21]));
    m.order_reference_number = load_be64(p + 22);
    return m;
  }
  friend bool operator==(const OrderPriorityUpdate&, const OrderPriorityUpdate&) = default;
};

class OrderPriorityUpdateView : public MessageView<OrderPriorityUpdate> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] std::uint64_t price() const noexcept { return load_be64(p() + 13); }
  [[nodiscard]] Display display() const noexcept { return static_cast<Display>(std::to_integer<char>(p()[21])); }
  [[nodiscard]] std::uint64_t order_reference_number() const noexcept { return load_be64(p() + 22); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderPriorityUpdateView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Price", v.price());
  f("Display", v.display());
  f("OrderReferenceNumber", v.order_reference_number());
}

// s3.12 Order Modified; appendage only with a non-zero UserRefIdx
struct OrderModified {
  using Layout = layout::out::OrderModified;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderModified";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  Side side{Side::Buy};
  std::uint32_t quantity{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    p[13] = static_cast<std::byte>(std::to_underlying(side));
    store_be32(p + 14, quantity);
  }
  [[nodiscard]] static OrderModified decode_base(const std::byte* p) noexcept {
    OrderModified m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.side = static_cast<Side>(std::to_integer<char>(p[13]));
    m.quantity = load_be32(p + 14);
    return m;
  }
  friend bool operator==(const OrderModified&, const OrderModified&) = default;
};

class OrderModifiedView : public MessageView<OrderModified> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] Side side() const noexcept { return static_cast<Side>(std::to_integer<char>(p()[13])); }
  [[nodiscard]] std::uint32_t quantity() const noexcept { return load_be32(p() + 14); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderModifiedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Side", v.side());
  f("Quantity", v.quantity());
}

// s3.13 Order Restated (table title in the PDF is a copy-paste error)
struct OrderRestated {
  using Layout = layout::out::OrderRestated;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "OrderRestated";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  RestatedReason reason{RestatedReason::DisplayRefresh};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    p[13] = static_cast<std::byte>(std::to_underlying(reason));
  }
  [[nodiscard]] static OrderRestated decode_base(const std::byte* p) noexcept {
    OrderRestated m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.reason = static_cast<RestatedReason>(std::to_integer<char>(p[13]));
    return m;
  }
  friend bool operator==(const OrderRestated&, const OrderRestated&) = default;
};

class OrderRestatedView : public MessageView<OrderRestated> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] RestatedReason reason() const noexcept { return static_cast<RestatedReason>(std::to_integer<char>(p()[13])); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const OrderRestatedView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Reason", v.reason());
}

// s3.14 Mass Cancel Response
struct MassCancelResponse {
  using Layout = layout::out::MassCancelResponse;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "MassCancelResponse";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  Alpha<4> firm{};
  Alpha<8> symbol{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    firm.to_wire(p + 13);
    symbol.to_wire(p + 17);
  }
  [[nodiscard]] static MassCancelResponse decode_base(const std::byte* p) noexcept {
    MassCancelResponse m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.firm = Alpha<4>::from_wire(p + 13);
    m.symbol = Alpha<8>::from_wire(p + 17);
    return m;
  }
  friend bool operator==(const MassCancelResponse&, const MassCancelResponse&) = default;
};

class MassCancelResponseView : public MessageView<MassCancelResponse> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 13); }
  [[nodiscard]] Alpha<8> symbol() const noexcept { return Alpha<8>::from_wire(p() + 17); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const MassCancelResponseView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
  f("Symbol", v.symbol());
}

// s3.15 Disable Order Entry Response
struct DisableOrderEntryResponse {
  using Layout = layout::out::DisableOrderEntryResponse;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "DisableOrderEntryResponse";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  Alpha<4> firm{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    firm.to_wire(p + 13);
  }
  [[nodiscard]] static DisableOrderEntryResponse decode_base(const std::byte* p) noexcept {
    DisableOrderEntryResponse m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.firm = Alpha<4>::from_wire(p + 13);
    return m;
  }
  friend bool operator==(const DisableOrderEntryResponse&, const DisableOrderEntryResponse&) = default;
};

class DisableOrderEntryResponseView : public MessageView<DisableOrderEntryResponse> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 13); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const DisableOrderEntryResponseView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
}

// s3.16 Enable Order Entry Response
struct EnableOrderEntryResponse {
  using Layout = layout::out::EnableOrderEntryResponse;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "EnableOrderEntryResponse";

  std::uint64_t timestamp{};
  std::uint32_t user_ref_num{};
  Alpha<4> firm{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, user_ref_num);
    firm.to_wire(p + 13);
  }
  [[nodiscard]] static EnableOrderEntryResponse decode_base(const std::byte* p) noexcept {
    EnableOrderEntryResponse m;
    m.timestamp = load_be64(p + 1);
    m.user_ref_num = load_be32(p + 9);
    m.firm = Alpha<4>::from_wire(p + 13);
    return m;
  }
  friend bool operator==(const EnableOrderEntryResponse&, const EnableOrderEntryResponse&) = default;
};

class EnableOrderEntryResponseView : public MessageView<EnableOrderEntryResponse> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t user_ref_num() const noexcept { return load_be32(p() + 9); }
  [[nodiscard]] Alpha<4> firm() const noexcept { return Alpha<4>::from_wire(p() + 13); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const EnableOrderEntryResponseView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("UserRefNum", v.user_ref_num());
  f("Firm", v.firm());
}

// s3.17 Account Query Response; appendage only with a non-zero UserRefIdx
struct AccountQueryResponse {
  using Layout = layout::out::AccountQueryResponse;
  static constexpr char kType = Layout::kType;
  static constexpr Direction kDirection = Direction::Outbound;
  static constexpr AppendageRule kRule = Layout::kRule;
  static constexpr std::size_t kFixedLen = Layout::kFixedLen;
  static constexpr std::size_t kBaseLen = Layout::kBaseLen;
  static constexpr std::size_t kMinLen = Layout::kMinLen;
  static constexpr std::size_t kMaxLen = Layout::kMaxLen;
  static constexpr std::uint32_t kAllowedTags = Layout::kAllowedTags;
  static constexpr const char* kName = "AccountQueryResponse";

  std::uint64_t timestamp{};
  std::uint32_t next_user_ref_num{};

  // Writes the fixed part up to (not including) Appendage Length.
  void encode_base(std::byte* p) const noexcept {
    p[0] = static_cast<std::byte>(kType);
    store_be64(p + 1, timestamp);
    store_be32(p + 9, next_user_ref_num);
  }
  [[nodiscard]] static AccountQueryResponse decode_base(const std::byte* p) noexcept {
    AccountQueryResponse m;
    m.timestamp = load_be64(p + 1);
    m.next_user_ref_num = load_be32(p + 9);
    return m;
  }
  friend bool operator==(const AccountQueryResponse&, const AccountQueryResponse&) = default;
};

class AccountQueryResponseView : public MessageView<AccountQueryResponse> {
 public:
  using MessageView::MessageView;
  [[nodiscard]] std::uint64_t timestamp() const noexcept { return load_be64(p() + 1); }
  [[nodiscard]] std::uint32_t next_user_ref_num() const noexcept { return load_be32(p() + 9); }
};

// Calls f(name, value) for every fixed field after Type, in wire order.
template <class F>
void for_each_field(const AccountQueryResponseView& v, F&& f) {
  f("Timestamp", v.timestamp());
  f("NextUserRefNum", v.next_user_ref_num());
}

}  // namespace out

// Invokes f with the typed inbound view for `type`; returns false for an unknown type.
template <class F>
bool visit_inbound(char type, std::span<const std::byte> bytes, F&& f) {
  switch (type) {
    case 'O': f(in::EnterOrderView(bytes)); return true;
    case 'U': f(in::ReplaceOrderView(bytes)); return true;
    case 'X': f(in::CancelOrderView(bytes)); return true;
    case 'M': f(in::ModifyOrderView(bytes)); return true;
    case 'C': f(in::MassCancelView(bytes)); return true;
    case 'D': f(in::DisableOrderEntryView(bytes)); return true;
    case 'E': f(in::EnableOrderEntryView(bytes)); return true;
    case 'Q': f(in::AccountQueryView(bytes)); return true;
    default: return false;
  }
}

// Invokes f with the typed outbound view for `type`; returns false for an unknown type.
template <class F>
bool visit_outbound(char type, std::span<const std::byte> bytes, F&& f) {
  switch (type) {
    case 'S': f(out::SystemEventView(bytes)); return true;
    case 'A': f(out::OrderAcceptedView(bytes)); return true;
    case 'U': f(out::OrderReplacedView(bytes)); return true;
    case 'C': f(out::OrderCanceledView(bytes)); return true;
    case 'D': f(out::AiqCanceledView(bytes)); return true;
    case 'E': f(out::OrderExecutedView(bytes)); return true;
    case 'B': f(out::BrokenTradeView(bytes)); return true;
    case 'J': f(out::RejectedView(bytes)); return true;
    case 'P': f(out::CancelPendingView(bytes)); return true;
    case 'I': f(out::CancelRejectView(bytes)); return true;
    case 'T': f(out::OrderPriorityUpdateView(bytes)); return true;
    case 'M': f(out::OrderModifiedView(bytes)); return true;
    case 'R': f(out::OrderRestatedView(bytes)); return true;
    case 'X': f(out::MassCancelResponseView(bytes)); return true;
    case 'G': f(out::DisableOrderEntryResponseView(bytes)); return true;
    case 'K': f(out::EnableOrderEntryResponseView(bytes)); return true;
    case 'Q': f(out::AccountQueryResponseView(bytes)); return true;
    default: return false;
  }
}

// Decoded appendage: one member per registry tag plus a presence mask.
struct TagSet {
  std::uint32_t present = 0;
  std::uint64_t secondary_ord_ref_num{};
  Alpha<4> firm{};
  std::uint32_t min_qty{};
  CustomerType customer_type{};
  std::uint32_t max_floor{};
  PriceType price_type{};
  std::int32_t peg_offset{};
  std::uint64_t discretion_price{};
  DiscretionPriceType discretion_price_type{};
  std::int32_t discretion_peg_offset{};
  PostOnly post_only{};
  std::uint32_t random_reserves{};
  Alpha<4> route{};
  std::uint32_t expire_time{};
  TradeNow trade_now{};
  HandleInst handle_inst{};
  BboWeightIndicator bbo_weight_indicator{};
  std::uint32_t display_quantity{};
  std::uint64_t display_price{};
  std::uint16_t group_id{};
  SharesLocated shares_located{};
  Alpha<4> locate_broker{};
  Side side{};
  std::uint8_t user_ref_idx{};
  AiqStrategy aiq_strategy{};
  Alpha<2> aiq_group_id{};

  [[nodiscard]] bool has(Tag t) const noexcept { return (present & tag_bit(t)) != 0; }
  void clear(Tag t) noexcept { present &= ~tag_bit(t); }
  TagSet& set_secondary_ord_ref_num(std::uint64_t v) noexcept {
    secondary_ord_ref_num = v;
    present |= tag_bit(Tag::SecondaryOrdRefNum);
    return *this;
  }
  TagSet& set_firm(Alpha<4> v) noexcept {
    firm = v;
    present |= tag_bit(Tag::Firm);
    return *this;
  }
  TagSet& set_min_qty(std::uint32_t v) noexcept {
    min_qty = v;
    present |= tag_bit(Tag::MinQty);
    return *this;
  }
  TagSet& set_customer_type(CustomerType v) noexcept {
    customer_type = v;
    present |= tag_bit(Tag::CustomerType);
    return *this;
  }
  TagSet& set_max_floor(std::uint32_t v) noexcept {
    max_floor = v;
    present |= tag_bit(Tag::MaxFloor);
    return *this;
  }
  TagSet& set_price_type(PriceType v) noexcept {
    price_type = v;
    present |= tag_bit(Tag::PriceType);
    return *this;
  }
  TagSet& set_peg_offset(std::int32_t v) noexcept {
    peg_offset = v;
    present |= tag_bit(Tag::PegOffset);
    return *this;
  }
  TagSet& set_discretion_price(std::uint64_t v) noexcept {
    discretion_price = v;
    present |= tag_bit(Tag::DiscretionPrice);
    return *this;
  }
  TagSet& set_discretion_price_type(DiscretionPriceType v) noexcept {
    discretion_price_type = v;
    present |= tag_bit(Tag::DiscretionPriceType);
    return *this;
  }
  TagSet& set_discretion_peg_offset(std::int32_t v) noexcept {
    discretion_peg_offset = v;
    present |= tag_bit(Tag::DiscretionPegOffset);
    return *this;
  }
  TagSet& set_post_only(PostOnly v) noexcept {
    post_only = v;
    present |= tag_bit(Tag::PostOnly);
    return *this;
  }
  TagSet& set_random_reserves(std::uint32_t v) noexcept {
    random_reserves = v;
    present |= tag_bit(Tag::RandomReserves);
    return *this;
  }
  TagSet& set_route(Alpha<4> v) noexcept {
    route = v;
    present |= tag_bit(Tag::Route);
    return *this;
  }
  TagSet& set_expire_time(std::uint32_t v) noexcept {
    expire_time = v;
    present |= tag_bit(Tag::ExpireTime);
    return *this;
  }
  TagSet& set_trade_now(TradeNow v) noexcept {
    trade_now = v;
    present |= tag_bit(Tag::TradeNow);
    return *this;
  }
  TagSet& set_handle_inst(HandleInst v) noexcept {
    handle_inst = v;
    present |= tag_bit(Tag::HandleInst);
    return *this;
  }
  TagSet& set_bbo_weight_indicator(BboWeightIndicator v) noexcept {
    bbo_weight_indicator = v;
    present |= tag_bit(Tag::BBOWeightIndicator);
    return *this;
  }
  TagSet& set_display_quantity(std::uint32_t v) noexcept {
    display_quantity = v;
    present |= tag_bit(Tag::DisplayQuantity);
    return *this;
  }
  TagSet& set_display_price(std::uint64_t v) noexcept {
    display_price = v;
    present |= tag_bit(Tag::DisplayPrice);
    return *this;
  }
  TagSet& set_group_id(std::uint16_t v) noexcept {
    group_id = v;
    present |= tag_bit(Tag::GroupID);
    return *this;
  }
  TagSet& set_shares_located(SharesLocated v) noexcept {
    shares_located = v;
    present |= tag_bit(Tag::SharesLocated);
    return *this;
  }
  TagSet& set_locate_broker(Alpha<4> v) noexcept {
    locate_broker = v;
    present |= tag_bit(Tag::LocateBroker);
    return *this;
  }
  TagSet& set_side(Side v) noexcept {
    side = v;
    present |= tag_bit(Tag::Side);
    return *this;
  }
  TagSet& set_user_ref_idx(std::uint8_t v) noexcept {
    user_ref_idx = v;
    present |= tag_bit(Tag::UserRefIdx);
    return *this;
  }
  TagSet& set_aiq_strategy(AiqStrategy v) noexcept {
    aiq_strategy = v;
    present |= tag_bit(Tag::AIQStrategy);
    return *this;
  }
  TagSet& set_aiq_group_id(Alpha<2> v) noexcept {
    aiq_group_id = v;
    present |= tag_bit(Tag::AIQGroupID);
    return *this;
  }
  friend bool operator==(const TagSet& a, const TagSet& b) noexcept {
    if (a.present != b.present) return false;
    if (a.has(Tag::SecondaryOrdRefNum) && !(a.secondary_ord_ref_num == b.secondary_ord_ref_num)) return false;
    if (a.has(Tag::Firm) && !(a.firm == b.firm)) return false;
    if (a.has(Tag::MinQty) && !(a.min_qty == b.min_qty)) return false;
    if (a.has(Tag::CustomerType) && !(a.customer_type == b.customer_type)) return false;
    if (a.has(Tag::MaxFloor) && !(a.max_floor == b.max_floor)) return false;
    if (a.has(Tag::PriceType) && !(a.price_type == b.price_type)) return false;
    if (a.has(Tag::PegOffset) && !(a.peg_offset == b.peg_offset)) return false;
    if (a.has(Tag::DiscretionPrice) && !(a.discretion_price == b.discretion_price)) return false;
    if (a.has(Tag::DiscretionPriceType) && !(a.discretion_price_type == b.discretion_price_type)) return false;
    if (a.has(Tag::DiscretionPegOffset) && !(a.discretion_peg_offset == b.discretion_peg_offset)) return false;
    if (a.has(Tag::PostOnly) && !(a.post_only == b.post_only)) return false;
    if (a.has(Tag::RandomReserves) && !(a.random_reserves == b.random_reserves)) return false;
    if (a.has(Tag::Route) && !(a.route == b.route)) return false;
    if (a.has(Tag::ExpireTime) && !(a.expire_time == b.expire_time)) return false;
    if (a.has(Tag::TradeNow) && !(a.trade_now == b.trade_now)) return false;
    if (a.has(Tag::HandleInst) && !(a.handle_inst == b.handle_inst)) return false;
    if (a.has(Tag::BBOWeightIndicator) && !(a.bbo_weight_indicator == b.bbo_weight_indicator)) return false;
    if (a.has(Tag::DisplayQuantity) && !(a.display_quantity == b.display_quantity)) return false;
    if (a.has(Tag::DisplayPrice) && !(a.display_price == b.display_price)) return false;
    if (a.has(Tag::GroupID) && !(a.group_id == b.group_id)) return false;
    if (a.has(Tag::SharesLocated) && !(a.shares_located == b.shares_located)) return false;
    if (a.has(Tag::LocateBroker) && !(a.locate_broker == b.locate_broker)) return false;
    if (a.has(Tag::Side) && !(a.side == b.side)) return false;
    if (a.has(Tag::UserRefIdx) && !(a.user_ref_idx == b.user_ref_idx)) return false;
    if (a.has(Tag::AIQStrategy) && !(a.aiq_strategy == b.aiq_strategy)) return false;
    if (a.has(Tag::AIQGroupID) && !(a.aiq_group_id == b.aiq_group_id)) return false;
    return true;
  }
};

// Writes every present tag in ascending tag order.
inline void put_tags(TagValueWriter& w, const TagSet& s) noexcept {
  if (s.has(Tag::SecondaryOrdRefNum)) w.put_u64(Tag::SecondaryOrdRefNum, s.secondary_ord_ref_num);
  if (s.has(Tag::Firm)) w.put_alpha(Tag::Firm, s.firm);
  if (s.has(Tag::MinQty)) w.put_u32(Tag::MinQty, s.min_qty);
  if (s.has(Tag::CustomerType)) w.put_char(Tag::CustomerType, std::to_underlying(s.customer_type));
  if (s.has(Tag::MaxFloor)) w.put_u32(Tag::MaxFloor, s.max_floor);
  if (s.has(Tag::PriceType)) w.put_char(Tag::PriceType, std::to_underlying(s.price_type));
  if (s.has(Tag::PegOffset)) w.put_i32(Tag::PegOffset, s.peg_offset);
  if (s.has(Tag::DiscretionPrice)) w.put_u64(Tag::DiscretionPrice, s.discretion_price);
  if (s.has(Tag::DiscretionPriceType)) w.put_char(Tag::DiscretionPriceType, std::to_underlying(s.discretion_price_type));
  if (s.has(Tag::DiscretionPegOffset)) w.put_i32(Tag::DiscretionPegOffset, s.discretion_peg_offset);
  if (s.has(Tag::PostOnly)) w.put_char(Tag::PostOnly, std::to_underlying(s.post_only));
  if (s.has(Tag::RandomReserves)) w.put_u32(Tag::RandomReserves, s.random_reserves);
  if (s.has(Tag::Route)) w.put_alpha(Tag::Route, s.route);
  if (s.has(Tag::ExpireTime)) w.put_u32(Tag::ExpireTime, s.expire_time);
  if (s.has(Tag::TradeNow)) w.put_char(Tag::TradeNow, std::to_underlying(s.trade_now));
  if (s.has(Tag::HandleInst)) w.put_char(Tag::HandleInst, std::to_underlying(s.handle_inst));
  if (s.has(Tag::BBOWeightIndicator)) w.put_char(Tag::BBOWeightIndicator, std::to_underlying(s.bbo_weight_indicator));
  if (s.has(Tag::DisplayQuantity)) w.put_u32(Tag::DisplayQuantity, s.display_quantity);
  if (s.has(Tag::DisplayPrice)) w.put_u64(Tag::DisplayPrice, s.display_price);
  if (s.has(Tag::GroupID)) w.put_u16(Tag::GroupID, s.group_id);
  if (s.has(Tag::SharesLocated)) w.put_char(Tag::SharesLocated, std::to_underlying(s.shares_located));
  if (s.has(Tag::LocateBroker)) w.put_alpha(Tag::LocateBroker, s.locate_broker);
  if (s.has(Tag::Side)) w.put_char(Tag::Side, std::to_underlying(s.side));
  if (s.has(Tag::UserRefIdx)) w.put_u8(Tag::UserRefIdx, s.user_ref_idx);
  if (s.has(Tag::AIQStrategy)) w.put_char(Tag::AIQStrategy, std::to_underlying(s.aiq_strategy));
  if (s.has(Tag::AIQGroupID)) w.put_alpha(Tag::AIQGroupID, s.aiq_group_id);
}

// Fills `out` from an appendage. Unknown tags are skipped (clients must tolerate
// them, FAQ Q8); a later duplicate overwrites an earlier one. Returns false on a
// malformed element or a known tag whose value has the wrong size.
[[nodiscard]] inline bool parse_tags(TagValueRange range, TagSet& out) noexcept {
  TagValueIterator it = range.begin();
  for (; it != std::default_sentinel; ++it) {
    const TagValue& tv = *it;
    const TagDesc* d = find_tag(tv.tag);
    if (d == nullptr) continue;
    if (tv.value.size() != d->value_len) return false;
    switch (static_cast<Tag>(tv.tag)) {
      case Tag::SecondaryOrdRefNum: out.set_secondary_ord_ref_num(tv.u64()); break;
      case Tag::Firm: out.set_firm(tv.alpha<4>()); break;
      case Tag::MinQty: out.set_min_qty(tv.u32()); break;
      case Tag::CustomerType: out.set_customer_type(static_cast<CustomerType>(tv.ch())); break;
      case Tag::MaxFloor: out.set_max_floor(tv.u32()); break;
      case Tag::PriceType: out.set_price_type(static_cast<PriceType>(tv.ch())); break;
      case Tag::PegOffset: out.set_peg_offset(tv.i32()); break;
      case Tag::DiscretionPrice: out.set_discretion_price(tv.u64()); break;
      case Tag::DiscretionPriceType: out.set_discretion_price_type(static_cast<DiscretionPriceType>(tv.ch())); break;
      case Tag::DiscretionPegOffset: out.set_discretion_peg_offset(tv.i32()); break;
      case Tag::PostOnly: out.set_post_only(static_cast<PostOnly>(tv.ch())); break;
      case Tag::RandomReserves: out.set_random_reserves(tv.u32()); break;
      case Tag::Route: out.set_route(tv.alpha<4>()); break;
      case Tag::ExpireTime: out.set_expire_time(tv.u32()); break;
      case Tag::TradeNow: out.set_trade_now(static_cast<TradeNow>(tv.ch())); break;
      case Tag::HandleInst: out.set_handle_inst(static_cast<HandleInst>(tv.ch())); break;
      case Tag::BBOWeightIndicator: out.set_bbo_weight_indicator(static_cast<BboWeightIndicator>(tv.ch())); break;
      case Tag::DisplayQuantity: out.set_display_quantity(tv.u32()); break;
      case Tag::DisplayPrice: out.set_display_price(tv.u64()); break;
      case Tag::GroupID: out.set_group_id(tv.u16()); break;
      case Tag::SharesLocated: out.set_shares_located(static_cast<SharesLocated>(tv.ch())); break;
      case Tag::LocateBroker: out.set_locate_broker(tv.alpha<4>()); break;
      case Tag::Side: out.set_side(static_cast<Side>(tv.ch())); break;
      case Tag::UserRefIdx: out.set_user_ref_idx(tv.u8()); break;
      case Tag::AIQStrategy: out.set_aiq_strategy(static_cast<AiqStrategy>(tv.ch())); break;
      case Tag::AIQGroupID: out.set_aiq_group_id(tv.alpha<2>()); break;
    }
  }
  return !it.malformed();
}

}  // namespace lle::ouch50
