#!/usr/bin/env python3
"""Render the DST bug ledger as Markdown on stdout (docs/plan/09 §10).

    python3 tools/ledger/gen_ledger_md.py [--ledger sim/ledger/bugs.yaml]
                                          [--verified results.jsonl] > docs/testing/bug-ledger.md

The published count is the *verified* count: pass --verified with the JSON
lines written by verify_bugs.py --json; without it, counted bugs are listed
as "unverified" and the verified count is 0. The output is deterministic
(sorted by id, no timestamps) so regenerating it is a no-op when nothing changed.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ledger  # noqa: E402

RULES = """\
A bug counts only if all of the following hold (applied mechanically by `tools/ledger/ledger.py`):

1. It is in production code, not harness code.
2. It was found by `exsim`. Fuzzer findings go to `fuzz/ledger/` and count for T14 only.
3. It reproduces from `seed@sha_found`. Until the fix is committed and tagged, `sha_found` may be
   `uncommitted` with a `found_patch` that reverts the fix; it then reproduces from the working
   tree plus that patch.
4. It has a distinct root cause (deduplicated by fix).
5. It is fixed, with a seed-independent regression test.

Never counted: canary faults (`exsim --canary`), mutation-testing mutants, determinism bugs in
the harness itself, and deliberately planted bugs of any kind. The published number is the
verified count (`tools/ledger/verify_bugs.py`, weekly and on every ledger change)."""


def cell(v: object) -> str:
    if v is None or v == "":
        return "-"
    if isinstance(v, list):
        return ", ".join(str(x) for x in v) or "-"
    return str(v).replace("|", "\\|").replace("\n", " ")


def short(sha: object) -> str:
    if sha == ledger.UNCOMMITTED:
        return str(sha)
    return cell(sha)[:10] if isinstance(sha, str) else cell(sha)


def load_verified(path: str | None) -> dict[str, dict]:
    out: dict[str, dict] = {}
    if not path:
        return out
    for line in Path(path).read_text().splitlines():
        if line.strip():
            rec = json.loads(line)
            if "id" in rec:
                out[rec["id"]] = rec
    return out


def render(data: dict, verified: dict[str, dict], source: str) -> str:
    bugs = sorted((b for b in data["bugs"] if isinstance(b, dict)), key=lambda b: str(b.get("id")))
    problems = ledger.validate(data)
    counted = [b for b in bugs if b.get("counted") is True]
    ok = [b for b in counted if verified.get(str(b.get("id")), {}).get("verified") is True]
    out = []
    out.append("# DST bug ledger")
    out.append("")
    out.append(f"<!-- Generated by tools/ledger/gen_ledger_md.py from {source}. Do not edit by hand. -->")
    out.append("")
    out.append("| | Count |")
    out.append("|---|---|")
    out.append(f"| Ledger entries | {len(bugs)} |")
    out.append(f"| Counted (claimed) | {len(counted)} |")
    out.append(f"| **Verified (published)** | **{len(ok)}** |")
    out.append(f"| Never counted (canary, mutant, harness, planted) | "
               f"{sum(1 for b in bugs if b.get('category') in ledger.NEVER_COUNTED)} |")
    out.append("")
    if problems:
        out.append("> **Ledger validation problems** (fix `sim/ledger/bugs.yaml`):")
        for p in problems:
            out.append(f"> - {p}")
        out.append("")
    out.append("## Counting rules")
    out.append("")
    out.append(RULES)
    out.append("")
    out.append("## Entries")
    out.append("")
    if not bugs:
        out.append("No entries yet.")
        out.append("")
    else:
        out.append("| ID | Title | Component | Targets | Oracle | Seed @ sha_found | Fix | Regression test | Counted | Verified |")
        out.append("|---|---|---|---|---|---|---|---|---|---|")
        for b in bugs:
            v = verified.get(str(b.get("id")))
            vstate = "-" if b.get("counted") is not True else ("yes" if v and v.get("verified") else "unverified")
            seed = ledger.parse_seed(b.get("seed"))
            seed_s = f"0x{seed:016x}" if seed is not None else cell(b.get("seed"))
            out.append(
                f"| {cell(b.get('id'))} | {cell(b.get('title'))} | {cell(b.get('component'))} | {cell(b.get('targets'))} "
                f"| {cell(b.get('oracle'))} | `{seed_s}` @ `{short(b.get('sha_found'))}` | `{short(b.get('fix_sha'))}` "
                f"| {cell(b.get('regression_test'))} | {'yes' if b.get('counted') is True else 'no'} | {vstate} |")
        out.append("")
        out.append("## Details")
        out.append("")
        for b in bugs:
            out.append(f"### {cell(b.get('id'))}: {cell(b.get('title'))}")
            out.append("")
            for f in ledger.FIELDS:
                if f.name in ("id", "title"):
                    continue
                v = b.get(f.name)
                if f.name == "signature":
                    sig = ledger.parse_signature(v)
                    v = ledger.format_signature(sig) if sig else v
                out.append(f"- **{f.name}**: {cell(v)}")
            if b.get("counted") is True:
                reasons = ledger.counting_violations(b)
                out.append(f"- **counting rules**: {'all hold' if not reasons else '; '.join(reasons)}")
            out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", default=str(ledger.DEFAULT_LEDGER))
    ap.add_argument("--verified", help="JSON lines from verify_bugs.py --json")
    a = ap.parse_args()
    path = Path(a.ledger)
    data = ledger.load(path)
    try:
        source = str(path.resolve().relative_to(ledger.REPO))
    except ValueError:
        source = path.name
    sys.stdout.write(render(data, load_verified(a.verified), source))
    return 0


if __name__ == "__main__":
    sys.exit(main())
